version: "3.7"

services:
  postgres:
    env_file: ./server/.env
    image: postgres
    ports: 
      - '5432:5432'
    volumes:
      - mitwelten-dev-db:/var/lib/postgresql/data
  api:
    env_file: ./server/.env
    depends_on:
      - postgres
    ports: 
      - '8080:8080'
    command: npm start
    restart: always
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: 22fsimvs31/mitwelten-fs22-imvs31:latest
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
volumes:
  nodemodules: {}
  mitwelten-dev-db:
