# Copyright (c) 2022 FHNW, Switzerland. All rights reserved.
# Licensed under MIT License, see LICENSE for details.

name: Continuous Integration

on: [push]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install Node dependencies
        run: npm ci

      - name: Lint frontend project
        run: npm run lint

      - name: Check code style of frontend
        run: npm run prettier

      - name: Build frontend
        run: npm run build

  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install Node dependencies
        run: npm ci

      - name: Lint backend project
        run: npm run lint

      - name: Check code style of backend
        run: npm run prettier

      - name: Build backend
        run: npm run build:server

  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install Node dependencies
        run: npm ci

      - name: Test backend
        run: npm test
